import random

class serene_randomizer():
    def __init__(self):
        self.blackboard = None
        self.environment = None
        return

    def set_blackboard_and_environment(self, blackboard, environment):
        self.blackboard = blackboard
        self.environment = environment
        return

    def r_0_0(self, node):
        return (0)

    def r_0_1(self, node):
        return (1)

    def r_0_2(self, node):
        return (2)

    def r_0_3(self, node):
        return (3)

    def r_0_4(self, node):
        return (4)

    def r_0_5(self, node):
        return (5)

    def r_0_6(self, node):
        return (6)

    def r_0_7(self, node):
        return (7)

    def r_0_8(self, node):
        return (8)

    def r_0_9(self, node):
        return (9)

    def r_0_10(self, node):
        return (10)

    def r_0_11(self, node):
        return (11)

    def r_0_12(self, node):
        return (12)

    def r_0_13(self, node):
        return (13)

    def r_0_14(self, node):
        return (14)

    def r_0_15(self, node):
        return (15)

    def r_0_16(self, node):
        return (16)

    def r_0_17(self, node):
        return (17)

    def r_0_18(self, node):
        return (18)

    def r_0_19(self, node):
        return (19)

    def r_0(self, node):
        random_val = random.randint(0, 19)
        function_name = 'r_0_' + str(random_val)
        function = getattr(self, function_name)
        return function(node)

    #---------------------
    def r_1_0(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 0)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 0)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 0)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 0)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 0)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 0)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 0)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 0)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 0)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 0)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 0)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 0)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 0)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 0)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 0)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 0)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 0)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 0)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 0)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 0))) else 0))

    def r_1_1(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 1)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 1)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 1)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 1)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 1)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 1)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 1)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 1)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 1)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 1)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 1)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 1)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 1)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 1)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 1)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 1)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 1)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 1)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 1)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 1))) else 1))

    def r_1_2(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 2)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 2)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 2)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 2)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 2)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 2)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 2)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 2)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 2)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 2)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 2)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 2)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 2)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 2)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 2)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 2)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 2)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 2)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 2)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 2))) else 2))

    def r_1_3(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 3)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 3)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 3)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 3)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 3)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 3)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 3)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 3)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 3)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 3)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 3)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 3)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 3)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 3)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 3)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 3)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 3)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 3)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 3)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 3))) else 3))

    def r_1_4(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 4)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 4)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 4)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 4)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 4)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 4)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 4)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 4)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 4)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 4)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 4)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 4)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 4)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 4)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 4)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 4)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 4)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 4)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 4)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 4))) else 4))

    def r_1_5(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 5)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 5)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 5)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 5)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 5)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 5)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 5)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 5)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 5)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 5)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 5)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 5)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 5)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 5)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 5)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 5)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 5)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 5)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 5)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 5))) else 5))

    def r_1_6(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 6)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 6)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 6)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 6)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 6)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 6)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 6)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 6)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 6)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 6)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 6)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 6)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 6)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 6)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 6)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 6)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 6)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 6)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 6)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 6))) else 6))

    def r_1_7(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 7)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 7)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 7)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 7)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 7)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 7)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 7)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 7)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 7)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 7)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 7)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 7)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 7)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 7)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 7)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 7)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 7)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 7)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 7)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 7))) else 7))

    def r_1_8(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 8)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 8)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 8)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 8)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 8)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 8)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 8)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 8)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 8)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 8)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 8)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 8)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 8)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 8)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 8)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 8)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 8)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 8)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 8)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 8))) else 8))

    def r_1_9(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 9)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 9)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 9)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 9)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 9)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 9)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 9)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 9)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 9)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 9)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 9)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 9)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 9)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 9)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 9)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 9)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 9)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 9)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 9)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 9))) else 9))

    def r_1_10(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 10)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 10)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 10)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 10)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 10)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 10)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 10)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 10)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 10)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 10)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 10)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 10)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 10)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 10)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 10)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 10)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 10)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 10)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 10)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 10))) else 10))

    def r_1_11(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 11)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 11)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 11)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 11)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 11)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 11)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 11)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 11)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 11)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 11)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 11)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 11)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 11)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 11)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 11)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 11)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 11)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 11)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 11)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 11))) else 11))

    def r_1_12(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 12)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 12)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 12)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 12)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 12)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 12)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 12)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 12)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 12)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 12)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 12)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 12)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 12)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 12)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 12)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 12)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 12)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 12)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 12)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 12))) else 12))

    def r_1_13(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 13)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 13)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 13)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 13)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 13)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 13)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 13)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 13)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 13)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 13)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 13)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 13)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 13)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 13)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 13)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 13)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 13)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 13)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 13)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 13))) else 13))

    def r_1_14(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 14)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 14)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 14)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 14)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 14)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 14)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 14)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 14)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 14)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 14)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 14)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 14)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 14)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 14)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 14)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 14)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 14)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 14)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 14)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 14))) else 14))

    def r_1_15(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 15)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 15)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 15)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 15)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 15)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 15)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 15)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 15)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 15)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 15)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 15)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 15)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 15)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 15)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 15)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 15)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 15)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 15)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 15)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 15))) else 15))

    def r_1_16(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 16)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 16)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 16)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 16)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 16)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 16)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 16)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 16)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 16)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 16)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 16)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 16)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 16)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 16)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 16)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 16)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 16)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 16)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 16)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 16))) else 16))

    def r_1_17(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 17)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 17)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 17)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 17)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 17)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 17)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 17)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 17)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 17)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 17)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 17)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 17)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 17)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 17)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 17)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 17)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 17)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 17)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 17)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 17))) else 17))

    def r_1_18(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 18)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 18)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 18)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 18)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 18)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 18)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 18)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 18)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 18)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 18)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 18)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 18)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 18)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 18)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 18)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 18)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 18)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 18)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 18)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 18))) else 18))

    def r_1_19(self, node):
        return ((19 if (((self.blackboard.obstacles_sort_x(0) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(1) == 19)) or ((self.blackboard.obstacles_sort_x(2) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(3) == 19)) or ((self.blackboard.obstacles_sort_x(4) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(5) == 19)) or ((self.blackboard.obstacles_sort_x(6) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(7) == 19)) or ((self.blackboard.obstacles_sort_x(8) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(9) == 19)) or ((self.blackboard.obstacles_sort_x(10) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(11) == 19)) or ((self.blackboard.obstacles_sort_x(12) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(13) == 19)) or ((self.blackboard.obstacles_sort_x(14) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(15) == 19)) or ((self.blackboard.obstacles_sort_x(16) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(17) == 19)) or ((self.blackboard.obstacles_sort_x(18) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(19) == 19)) or ((self.blackboard.obstacles_sort_x(20) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(21) == 19)) or ((self.blackboard.obstacles_sort_x(22) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(23) == 19)) or ((self.blackboard.obstacles_sort_x(24) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(25) == 19)) or ((self.blackboard.obstacles_sort_x(26) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(27) == 19)) or ((self.blackboard.obstacles_sort_x(28) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(29) == 19)) or ((self.blackboard.obstacles_sort_x(30) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(31) == 19)) or ((self.blackboard.obstacles_sort_x(32) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(33) == 19)) or ((self.blackboard.obstacles_sort_x(34) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(35) == 19)) or ((self.blackboard.obstacles_sort_x(36) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(37) == 19)) or ((self.blackboard.obstacles_sort_x(38) == self.blackboard.waypoint_x) and (self.blackboard.obstacles_sort_x(39) == 19))) else 19))

    def r_1(self, node):
        random_val = random.randint(0, 19)
        function_name = 'r_1_' + str(random_val)
        function = getattr(self, function_name)
        return function(node)

    #---------------------
