/******************************************************************************
 * monitor code generated by NuRV (NuRV_lite version: 1.0.0)
 *
 * LTL:  G system.drone_x < 3
 *
 * nbits_obs: 3 (width: 1), nbits_all: 3 (width: 1)
 * reset_table: 1, trans_table: 1, input_filter: 0
 ******************************************************************************/

#ifndef NURV_CODEGEN_MONITOR_MONITOR_SIMPLEST
#define NURV_CODEGEN_MONITOR_MONITOR_SIMPLEST

#ifndef NURV_CODEGEN_TYPES
#define NURV_CODEGEN_TYPES 1
typedef enum {
  RV_UNKNOWN     = 0,
  RV_TRUE        = 1,
  RV_FALSE       = 2,
  RV_ERROR       = 3,
  RV_INVALID_ARG = 4,
  RV_INVALID_LOC = 5,
  RV_INVALID_MON = 6,
} RV_value;

#ifdef __GNUC__
#define RV_value_string(z) \
     ({__typeof__(z) x = z; \
       (x == RV_UNKNOWN     ? "unknown" : \
        x == RV_TRUE        ? "true" : \
        x == RV_FALSE       ? "false" : \
        x == RV_ERROR       ? "out-of-model" : \
        x == RV_INVALID_ARG ? "invalid inputs" : \
        x == RV_INVALID_LOC ? "invalid location" : "");})
#else
#define RV_value_string(x) \
       (x == RV_UNKNOWN     ? "unknown" : \
        x == RV_TRUE        ? "true" : \
        x == RV_FALSE       ? "false" : \
        x == RV_ERROR       ? "out-of-model" : \
        x == RV_INVALID_ARG ? "invalid inputs" : \
        x == RV_INVALID_LOC ? "invalid location" : "")
#endif

typedef enum {
  NO_RESET   = 0,
  HARD_RESET = 1,
  SOFT_RESET = 2 
} RV_reset;
#endif /* NURV_CODEGEN_TYPES */

/* 1. old API */
int /* [out] (0 = unknown, 1 = true, 2 = false, 3 = error) */
  monitor_simplest
    (long /* [in] state */,
     int  /* [in] reset (0 = none, 1 = hard, 2 = soft) */,
     int* /* [in/out] current_loc */);

#define monitor_simplest_segment 30 /* number of 'bits' stored in each long state */
#define monitor_simplest_width   1 /* minimal value of 'width' in the function call */

/* 2. new API */
RV_value monitor_simplest_ex
  (long    *states,       /* [in] */
   size_t   width,        /* [in] (min: 1) */
   RV_reset reset,        /* [in] (HARD_RESET is necessary for the first call) */
   int     *current_loc); /* [in/out] (after HARD_RESET it is 1) */

/* constants used in the model */
#ifndef _nurv_constant_right
#define _nurv_constant_right
#define right 0
#endif
#ifndef _nurv_constant_left
#define _nurv_constant_left
#define left 1
#endif

/* INFO: input ordering:
   system_drone_x.1 (system.drone_x.1) : 0
   system_drone_x.0 (system.drone_x.0) : 1
   system_current_action.0 (system.current_action.0) : 2
*/

/* input data */
typedef struct {
  int system_drone_x;
  int system_current_action;
} monitor_simplest_input_t;

/* input masks (0: not observable, 1: observable) */
typedef struct {
  unsigned int system_drone_x : 1;
  unsigned int system_current_action : 1;
} monitor_simplest_mask_t;

/* 3. scalar API */
RV_value monitor_simplest_scalar
  (monitor_simplest_input_t *input,
   monitor_simplest_mask_t *masks, /* NULL (no masks) means fully observable */
   RV_reset reset,
   int *current_loc);

#endif /* NURV_CODEGEN_MONITOR_MONITOR_SIMPLEST */
