#!/bin/bash

rm ./size_models/wide_selector/stats

for i in {2..20}
do
  python3 btree_serene.py btree_creator.py create_root --root_args $i 0 False --min_val 0 --max_val 1 > ./size_models/wide_selector/$i.smv
  ~/nuXmv -source command_list ./size_models/wide_selector/$i.smv >> ./size_models/wide_selector/stats
  echo $i
done

python3 process_stats.py ./size_models/wide_selector

rm ./size_models/wide_parallel_synch/stats

for i in {2..20}
do
  python3 btree_serene.py btree_creator.py create_root --root_args $i 1 False --min_val 0 --max_val 1 > ./size_models/wide_parallel_synch/$i.smv
  ~/nuXmv -source command_list ./size_models/wide_parallel_synch/$i.smv >> ./size_models/wide_parallel_synch/stats
  echo $i
done

python3 process_stats.py ./size_models/wide_parallel_synch

rm ./size_models/wide_parallel_unsynch/stats

for i in {2..20}
do
  python3 btree_serene.py btree_creator.py create_root --root_args $i 1 False --min_val 0 --max_val 1 > ./size_models/wide_parallel_unsynch/$i.smv
  ~/nuXmv -source command_list ./size_models/wide_parallel_unsynch/$i.smv >> ./size_models/wide_parallel_unsynch/stats
  echo $i
done

python3 process_stats.py ./size_models/wide_parallel_unsynch

rm ./size_models/binary_selector/stats

for i in {1..3}
do
  python3 btree_serene.py btree_creator.py create_root --root_args $i 0 True --min_val 0 --max_val 1 > ./size_models/binary_selector/$i.smv
  ~/nuXmv -source command_list ./size_models/binary_selector/$i.smv >> ./size_models/binary_selector/stats
  echo $i
done

python3 process_stats.py ./size_models/binary_selector


rm ./size_models/binary_parallel_synch/stats

for i in {1..3}
do
  python3 btree_serene.py btree_creator.py create_root --root_args $i 1 True --min_val 0 --max_val 1 > ./size_models/binary_parallel_synch/$i.smv
  ~/nuXmv -source command_list ./size_models/binary_parallel_synch/$i.smv >> ./size_models/binary_parallel_synch/stats
  echo $i
done

python3 process_stats.py ./size_models/binary_parallel_synch



rm ./size_models/binary_parallel_unsynch/stats

for i in {1..3}
do
  python3 btree_serene.py btree_creator.py create_root --root_args $i 2 True --min_val 0 --max_val 1 > ./size_models/binary_parallel_unsynch/$i.smv
  ~/nuXmv -source command_list ./size_models/binary_parallel_unsynch/$i.smv >> ./size_models/binary_parallel_unsynch/stats
  echo $i
done

python3 process_stats.py ./size_models/binary_parallel_unsynch



rm ./size_models/binary_parallel_unsynch_mix1/stats

for i in {1..3}
do
  python3 btree_serene.py btree_creator.py create_root --root_args $i 3 True --min_val 0 --max_val 1 > ./size_models/binary_parallel_unsynch_mix1/$i.smv
  ~/nuXmv -source command_list ./size_models/binary_parallel_unsynch_mix1/$i.smv >> ./size_models/binary_parallel_unsynch_mix1/stats
  echo $i
done

python3 process_stats.py ./size_models/binary_parallel_unsynch_mix1


rm ./size_models/binary_parallel_synch_mix1/stats

for i in {1..3}
do
  python3 btree_serene.py btree_creator.py create_root --root_args $i 4 True --min_val 0 --max_val 1 > ./size_models/binary_parallel_synch_mix1/$i.smv
  ~/nuXmv -source command_list ./size_models/binary_parallel_synch_mix1/$i.smv >> ./size_models/binary_parallel_synch_mix1/stats
  echo $i
done

python3 process_stats.py ./size_models/binary_parallel_synch_mix1


rm ./size_models/binary_parallel_synch_mix2/stats

for i in {1..3}
do
  python3 btree_serene.py btree_creator.py create_root --root_args $i 5 True --min_val 0 --max_val 1 > ./size_models/binary_parallel_synch_mix2/$i.smv
  ~/nuXmv -source command_list ./size_models/binary_parallel_synch_mix2/$i.smv >> ./size_models/binary_parallel_synch_mix2/stats
  echo $i
done

python3 process_stats.py ./size_models/binary_parallel_synch_mix2


rm ./size_models/binary_parallel_unsynch_mix2/stats

for i in {1..3}
do
  python3 btree_serene.py btree_creator.py create_root --root_args $i 6 True --min_val 0 --max_val 1 > ./size_models/binary_parallel_unsynch_mix2/$i.smv
  ~/nuXmv -source command_list ./size_models/binary_parallel_unsynch_mix2/$i.smv >> ./size_models/binary_parallel_unsynch_mix2/stats
  echo $i
done

python3 process_stats.py ./size_models/binary_parallel_unsynch_mix2
