module BTreeTargetInSight where
import BehaviorTreeCore
import BehaviorTreeBlackboard
import BehaviorTreeEnvironment
import SereneRandomizer
import SereneOperations



bTreeFunctionTargetInSight :: [BTreeNode] -> TreeLocation -> TrueMemoryStatus -> [TrueMemoryStorage] -> PartialMemoryStatus -> [PartialMemoryStorage] -> BTreeBlackboard -> BTreeEnvironment -> FutureChanges -> BTreeNodeOutput
bTreeFunctionTargetInSight _ nodeLocation _ _ _ _ blackboard environment futureChanges
  | ( (((abs ((boardCurX blackboard) - (envTarX environment))) + (abs ((boardCurY blackboard) - (envTarY environment)))) <= 4)&&(( (((abs ((indexIntoTreeX 0 (envTreeX blackboard environment)) - (envTarX environment))) + (abs ((indexIntoTreeY 0 (envTreeY blackboard environment)) - (envTarY environment)))) > 2)|| ( (((indexIntoTreeX 0 (envTreeX blackboard environment)) == (boardCurX blackboard)) && ((indexIntoTreeY 0 (envTreeY blackboard environment)) == (boardCurY blackboard)))|| ( (((indexIntoTreeX 0 (envTreeX blackboard environment)) == (envTarX environment)) && ((indexIntoTreeY 0 (envTreeY blackboard environment)) == (envTarY environment)))|| ( (((indexIntoTreeX 0 (envTreeX blackboard environment)) < (boardCurX blackboard)) && ((indexIntoTreeX 0 (envTreeX blackboard environment)) < (envTarX environment)))|| ( (((indexIntoTreeY 0 (envTreeY blackboard environment)) < (boardCurY blackboard)) && ((indexIntoTreeY 0 (envTreeY blackboard environment)) < (envTarY environment)))||((((indexIntoTreeX 0 (envTreeX blackboard environment)) > (boardCurX blackboard)) && ((indexIntoTreeX 0 (envTreeX blackboard environment)) > (envTarX environment))) || (((indexIntoTreeY 0 (envTreeY blackboard environment)) > (boardCurY blackboard)) && ((indexIntoTreeY 0 (envTreeY blackboard environment)) > (envTarY environment))))))))) && ( (((abs ((indexIntoTreeX 1 (envTreeX blackboard environment)) - (envTarX environment))) + (abs ((indexIntoTreeY 1 (envTreeY blackboard environment)) - (envTarY environment)))) > 2)|| ( (((indexIntoTreeX 1 (envTreeX blackboard environment)) == (boardCurX blackboard)) && ((indexIntoTreeY 1 (envTreeY blackboard environment)) == (boardCurY blackboard)))|| ( (((indexIntoTreeX 1 (envTreeX blackboard environment)) == (envTarX environment)) && ((indexIntoTreeY 1 (envTreeY blackboard environment)) == (envTarY environment)))|| ( (((indexIntoTreeX 1 (envTreeX blackboard environment)) < (boardCurX blackboard)) && ((indexIntoTreeX 1 (envTreeX blackboard environment)) < (envTarX environment)))|| ( (((indexIntoTreeY 1 (envTreeY blackboard environment)) < (boardCurY blackboard)) && ((indexIntoTreeY 1 (envTreeY blackboard environment)) < (envTarY environment)))||((((indexIntoTreeX 1 (envTreeX blackboard environment)) > (boardCurX blackboard)) && ((indexIntoTreeX 1 (envTreeX blackboard environment)) > (envTarX environment))) || (((indexIntoTreeY 1 (envTreeY blackboard environment)) > (boardCurY blackboard)) && ((indexIntoTreeY 1 (envTreeY blackboard environment)) > (envTarY environment))))))))))) = (Success, [], [], blackboard, environment, futureChanges)
  | otherwise = (Failure, [], [], blackboard, environment, futureChanges)