/******************************************************************************
 * monitor code generated by NuRV (NuRV_lite version: 1.0.0)
 *
 * LTL:  G system.drone_x != 1
 *
 * nbits_obs: 5 (width: 1), nbits_all: 5 (width: 1)
 * reset_table: 1, trans_table: 1, input_filter: 0
 ******************************************************************************/

#include <stdio.h>  /* for FILE, etc. */
#include <stddef.h> /* for size_t */
#include <stdlib.h> /* for bsearch() */
#include <stdint.h> /* for int8_t, etc. */
#include <string.h> /* for memset() */
#include <assert.h> /* for assert() */

#include "monitor.h"

/* maximum number of elements in each line: 20 */
static int reset_table[50] = {
  0, 1, 49, 42, 42, 42, 49, 42, 42, 42, 49, 42, 49, 49, 49, 42, 35, 34, 35, 35, /* L1 */
  34, 34, 34, 34, 35, 35, 35, 34, 35, 35, 34, 34, 34, 34, 34, 35, 42, 42, 42, 49, /* L2 */
  42, 42, 42, 49, 49, 42, 49, 49, 42, 49
};

/* for internal per-monitor use only */
typedef struct {
  long input;
  int output;
  int next_loc;
} trans_t;

/* maximum number of elements in each line: 4 */
static trans_t data_49[8] = {
  {0x0L, 0, 10}, {0x4L, 0, 2}, {0x8L, 2, 18}, {0xcL, 0, 4}, /* L1 */
  {0x10L, 0, 12}, {0x14L, 0, 6}, {0x18L, 2, 28}, {0x1cL, 0, 8} /* L2 */
};

static trans_t data_48[8] = {
  {0x2L, 2, 36}, {0x6L, 2, 37}, {0xaL, 2, 20}, {0xeL, 2, 38}, /* L1 */
  {0x12L, 2, 39}, {0x16L, 2, 40}, {0x1aL, 2, 30}, {0x1eL, 2, 41} /* L2 */
};

static trans_t data_47[8] = {
  {0x0L, 2, 43}, {0x4L, 2, 44}, {0x8L, 2, 18}, {0xcL, 2, 45}, /* L1 */
  {0x10L, 2, 46}, {0x14L, 2, 47}, {0x18L, 2, 28}, {0x1cL, 2, 48} /* L2 */
};

static trans_t data_46[8] = {
  {0x0L, 2, 43}, {0x4L, 2, 44}, {0x8L, 2, 18}, {0xcL, 2, 45}, /* L1 */
  {0x10L, 2, 46}, {0x14L, 2, 47}, {0x18L, 2, 28}, {0x1cL, 2, 48} /* L2 */
};

static trans_t data_45[8] = {
  {0x2L, 2, 36}, {0x6L, 2, 37}, {0xaL, 2, 20}, {0xeL, 2, 38}, /* L1 */
  {0x12L, 2, 39}, {0x16L, 2, 40}, {0x1aL, 2, 30}, {0x1eL, 2, 41} /* L2 */
};

static trans_t data_44[8] = {
  {0x0L, 2, 43}, {0x4L, 2, 44}, {0x8L, 2, 18}, {0xcL, 2, 45}, /* L1 */
  {0x10L, 2, 46}, {0x14L, 2, 47}, {0x18L, 2, 28}, {0x1cL, 2, 48} /* L2 */
};

static trans_t data_43[8] = {
  {0x0L, 2, 43}, {0x4L, 2, 44}, {0x8L, 2, 18}, {0xcL, 2, 45}, /* L1 */
  {0x10L, 2, 46}, {0x14L, 2, 47}, {0x18L, 2, 28}, {0x1cL, 2, 48} /* L2 */
};

static trans_t data_42[8] = {
  {0x2L, 0, 11}, {0x6L, 0, 3}, {0xaL, 2, 20}, {0xeL, 0, 5}, /* L1 */
  {0x12L, 0, 13}, {0x16L, 0, 7}, {0x1aL, 2, 30}, {0x1eL, 0, 9} /* L2 */
};

static trans_t data_41[8] = {
  {0x2L, 2, 36}, {0x6L, 2, 37}, {0xaL, 2, 20}, {0xeL, 2, 38}, /* L1 */
  {0x12L, 2, 39}, {0x16L, 2, 40}, {0x1aL, 2, 30}, {0x1eL, 2, 41} /* L2 */
};

static trans_t data_40[8] = {
  {0x2L, 2, 36}, {0x6L, 2, 37}, {0xaL, 2, 20}, {0xeL, 2, 38}, /* L1 */
  {0x12L, 2, 39}, {0x16L, 2, 40}, {0x1aL, 2, 30}, {0x1eL, 2, 41} /* L2 */
};

static trans_t data_39[8] = {
  {0x0L, 2, 43}, {0x4L, 2, 44}, {0x8L, 2, 18}, {0xcL, 2, 45}, /* L1 */
  {0x10L, 2, 46}, {0x14L, 2, 47}, {0x18L, 2, 28}, {0x1cL, 2, 48} /* L2 */
};

static trans_t data_38[8] = {
  {0x2L, 2, 36}, {0x6L, 2, 37}, {0xaL, 2, 20}, {0xeL, 2, 38}, /* L1 */
  {0x12L, 2, 39}, {0x16L, 2, 40}, {0x1aL, 2, 30}, {0x1eL, 2, 41} /* L2 */
};

static trans_t data_37[8] = {
  {0x2L, 2, 36}, {0x6L, 2, 37}, {0xaL, 2, 20}, {0xeL, 2, 38}, /* L1 */
  {0x12L, 2, 39}, {0x16L, 2, 40}, {0x1aL, 2, 30}, {0x1eL, 2, 41} /* L2 */
};

static trans_t data_36[8] = {
  {0x2L, 2, 36}, {0x6L, 2, 37}, {0xaL, 2, 20}, {0xeL, 2, 38}, /* L1 */
  {0x12L, 2, 39}, {0x16L, 2, 40}, {0x1aL, 2, 30}, {0x1eL, 2, 41} /* L2 */
};

static trans_t data_35[8] = {
  {0x1L, 2, 14}, {0x5L, 2, 16}, {0x9L, 2, 19}, {0xdL, 2, 22}, /* L1 */
  {0x11L, 2, 24}, {0x15L, 2, 26}, {0x19L, 2, 29}, {0x1dL, 2, 32} /* L2 */
};

static trans_t data_34[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_33[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_32[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_31[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_30[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_29[8] = {
  {0x1L, 2, 14}, {0x5L, 2, 16}, {0x9L, 2, 19}, {0xdL, 2, 22}, /* L1 */
  {0x11L, 2, 24}, {0x15L, 2, 26}, {0x19L, 2, 29}, {0x1dL, 2, 32} /* L2 */
};

static trans_t data_28[8] = {
  {0x1L, 2, 14}, {0x5L, 2, 16}, {0x9L, 2, 19}, {0xdL, 2, 22}, /* L1 */
  {0x11L, 2, 24}, {0x15L, 2, 26}, {0x19L, 2, 29}, {0x1dL, 2, 32} /* L2 */
};

static trans_t data_27[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_26[8] = {
  {0x1L, 2, 14}, {0x5L, 2, 16}, {0x9L, 2, 19}, {0xdL, 2, 22}, /* L1 */
  {0x11L, 2, 24}, {0x15L, 2, 26}, {0x19L, 2, 29}, {0x1dL, 2, 32} /* L2 */
};

static trans_t data_25[8] = {
  {0x1L, 2, 14}, {0x5L, 2, 16}, {0x9L, 2, 19}, {0xdL, 2, 22}, /* L1 */
  {0x11L, 2, 24}, {0x15L, 2, 26}, {0x19L, 2, 29}, {0x1dL, 2, 32} /* L2 */
};

static trans_t data_24[8] = {
  {0x1L, 2, 14}, {0x5L, 2, 16}, {0x9L, 2, 19}, {0xdL, 2, 22}, /* L1 */
  {0x11L, 2, 24}, {0x15L, 2, 26}, {0x19L, 2, 29}, {0x1dL, 2, 32} /* L2 */
};

static trans_t data_23[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_22[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_21[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_20[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_19[8] = {
  {0x1L, 2, 14}, {0x5L, 2, 16}, {0x9L, 2, 19}, {0xdL, 2, 22}, /* L1 */
  {0x11L, 2, 24}, {0x15L, 2, 26}, {0x19L, 2, 29}, {0x1dL, 2, 32} /* L2 */
};

static trans_t data_18[8] = {
  {0x1L, 2, 14}, {0x5L, 2, 16}, {0x9L, 2, 19}, {0xdL, 2, 22}, /* L1 */
  {0x11L, 2, 24}, {0x15L, 2, 26}, {0x19L, 2, 29}, {0x1dL, 2, 32} /* L2 */
};

static trans_t data_17[8] = {
  {0x3L, 2, 15}, {0x7L, 2, 17}, {0xbL, 2, 21}, {0xfL, 2, 23}, /* L1 */
  {0x13L, 2, 25}, {0x17L, 2, 27}, {0x1bL, 2, 31}, {0x1fL, 2, 33} /* L2 */
};

static trans_t data_16[8] = {
  {0x1L, 2, 14}, {0x5L, 2, 16}, {0x9L, 2, 19}, {0xdL, 2, 22}, /* L1 */
  {0x11L, 2, 24}, {0x15L, 2, 26}, {0x19L, 2, 29}, {0x1dL, 2, 32} /* L2 */
};

static trans_t data_15[8] = {
  {0x2L, 2, 36}, {0x6L, 2, 37}, {0xaL, 2, 20}, {0xeL, 2, 38}, /* L1 */
  {0x12L, 2, 39}, {0x16L, 2, 40}, {0x1aL, 2, 30}, {0x1eL, 2, 41} /* L2 */
};

static trans_t data_14[8] = {
  {0x0L, 2, 43}, {0x4L, 2, 44}, {0x8L, 2, 18}, {0xcL, 2, 45}, /* L1 */
  {0x10L, 2, 46}, {0x14L, 2, 47}, {0x18L, 2, 28}, {0x1cL, 2, 48} /* L2 */
};

static trans_t data_13[8] = {
  {0x0L, 0, 10}, {0x4L, 0, 2}, {0x8L, 2, 18}, {0xcL, 0, 4}, /* L1 */
  {0x10L, 0, 12}, {0x14L, 0, 6}, {0x18L, 2, 28}, {0x1cL, 0, 8} /* L2 */
};

static trans_t data_12[8] = {
  {0x0L, 0, 10}, {0x4L, 0, 2}, {0x8L, 2, 18}, {0xcL, 0, 4}, /* L1 */
  {0x10L, 0, 12}, {0x14L, 0, 6}, {0x18L, 2, 28}, {0x1cL, 0, 8} /* L2 */
};

static trans_t data_11[8] = {
  {0x2L, 0, 11}, {0x6L, 0, 3}, {0xaL, 2, 20}, {0xeL, 0, 5}, /* L1 */
  {0x12L, 0, 13}, {0x16L, 0, 7}, {0x1aL, 2, 30}, {0x1eL, 0, 9} /* L2 */
};

static trans_t data_10[8] = {
  {0x0L, 0, 10}, {0x4L, 0, 2}, {0x8L, 2, 18}, {0xcL, 0, 4}, /* L1 */
  {0x10L, 0, 12}, {0x14L, 0, 6}, {0x18L, 2, 28}, {0x1cL, 0, 8} /* L2 */
};

static trans_t data_9[8] = {
  {0x2L, 0, 11}, {0x6L, 0, 3}, {0xaL, 2, 20}, {0xeL, 0, 5}, /* L1 */
  {0x12L, 0, 13}, {0x16L, 0, 7}, {0x1aL, 2, 30}, {0x1eL, 0, 9} /* L2 */
};

static trans_t data_8[8] = {
  {0x2L, 0, 11}, {0x6L, 0, 3}, {0xaL, 2, 20}, {0xeL, 0, 5}, /* L1 */
  {0x12L, 0, 13}, {0x16L, 0, 7}, {0x1aL, 2, 30}, {0x1eL, 0, 9} /* L2 */
};

static trans_t data_7[8] = {
  {0x2L, 0, 11}, {0x6L, 0, 3}, {0xaL, 2, 20}, {0xeL, 0, 5}, /* L1 */
  {0x12L, 0, 13}, {0x16L, 0, 7}, {0x1aL, 2, 30}, {0x1eL, 0, 9} /* L2 */
};

static trans_t data_6[8] = {
  {0x0L, 0, 10}, {0x4L, 0, 2}, {0x8L, 2, 18}, {0xcL, 0, 4}, /* L1 */
  {0x10L, 0, 12}, {0x14L, 0, 6}, {0x18L, 2, 28}, {0x1cL, 0, 8} /* L2 */
};

static trans_t data_5[8] = {
  {0x2L, 0, 11}, {0x6L, 0, 3}, {0xaL, 2, 20}, {0xeL, 0, 5}, /* L1 */
  {0x12L, 0, 13}, {0x16L, 0, 7}, {0x1aL, 2, 30}, {0x1eL, 0, 9} /* L2 */
};

static trans_t data_4[8] = {
  {0x2L, 0, 11}, {0x6L, 0, 3}, {0xaL, 2, 20}, {0xeL, 0, 5}, /* L1 */
  {0x12L, 0, 13}, {0x16L, 0, 7}, {0x1aL, 2, 30}, {0x1eL, 0, 9} /* L2 */
};

static trans_t data_3[8] = {
  {0x2L, 0, 11}, {0x6L, 0, 3}, {0xaL, 2, 20}, {0xeL, 0, 5}, /* L1 */
  {0x12L, 0, 13}, {0x16L, 0, 7}, {0x1aL, 2, 30}, {0x1eL, 0, 9} /* L2 */
};

static trans_t data_2[8] = {
  {0x0L, 0, 10}, {0x4L, 0, 2}, {0x8L, 2, 18}, {0xcL, 0, 4}, /* L1 */
  {0x10L, 0, 12}, {0x14L, 0, 6}, {0x18L, 2, 28}, {0x1cL, 0, 8} /* L2 */
};

static trans_t data_1[32] = {
  {0x0L, 0, 10}, {0x1L, 2, 14}, {0x2L, 0, 11}, {0x3L, 2, 15}, /* L1 */
  {0x4L, 0, 2}, {0x5L, 2, 16}, {0x6L, 0, 3}, {0x7L, 2, 17}, /* L2 */
  {0x8L, 2, 18}, {0x9L, 2, 19}, {0xaL, 2, 20}, {0xbL, 2, 21}, /* L3 */
  {0xcL, 0, 4}, {0xdL, 2, 22}, {0xeL, 0, 5}, {0xfL, 2, 23}, /* L4 */
  {0x10L, 0, 12}, {0x11L, 2, 24}, {0x12L, 0, 13}, {0x13L, 2, 25}, /* L5 */
  {0x14L, 0, 6}, {0x15L, 2, 26}, {0x16L, 0, 7}, {0x17L, 2, 27}, /* L6 */
  {0x18L, 2, 28}, {0x19L, 2, 29}, {0x1aL, 2, 30}, {0x1bL, 2, 31}, /* L7 */
  {0x1cL, 0, 8}, {0x1dL, 2, 32}, {0x1eL, 0, 9}, {0x1fL, 2, 33} /* L8 */
};

static int data_cmp (const void *lhs, const void *rhs)
{
  const trans_t *_lhs = (const trans_t *)lhs;
  const trans_t *_rhs = (const trans_t *)rhs;

  return (_lhs -> input - _rhs -> input);
}

static trans_t* data_table[50] = {
  NULL, data_1, data_2, data_3, data_4, data_5, data_6, data_7, /* L1 */
  data_8, data_9, data_10, data_11, data_12, data_13, data_14, data_15, /* L2 */
  data_16, data_17, data_18, data_19, data_20, data_21, data_22, data_23, /* L3 */
  data_24, data_25, data_26, data_27, data_28, data_29, data_30, data_31, /* L4 */
  data_32, data_33, data_34, data_35, data_36, data_37, data_38, data_39, /* L5 */
  data_40, data_41, data_42, data_43, data_44, data_45, data_46, data_47, /* L6 */
  data_48, data_49
};

/* number of elements in each line: 20 */
static size_t size_table[50] = {
  0, 32, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, /* L1 */
  8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, /* L2 */
  8, 8, 8, 8, 8, 8, 8, 8, 8, 8
};

/* 3. main function (old API) */
int /* [out] (0 = unknown, 1 = true, 2 = false, 3 = error) */
  monitor
    (long state,       /* [in] */
     int  reset,       /* [in] (0 = none, 1 = hard, 2 = soft) */
     int *current_loc) /* [in/out] */
{
  long states[1], base = 1L;

  states[0] = (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;

  return monitor_ex (states, 1, reset, current_loc);
}

/* internal function (no input filtering) */
static RV_value monitor_internal
  (long    *inputs,      /* [in] */
   size_t   width,       /* [in] (min: 1) */
   RV_reset reset,       /* [in] */
   int     *current_loc) /* [in/out] */
{
  /* local variables */
  trans_t *table, key, *result; /* for bsearch() */
  size_t size;                  /* for bsearch() */
  RV_value output;

  /* validate inputs (part 1) */
  if (NULL == current_loc) {
    return RV_INVALID_LOC;
  }

  /* handle resets */
  if (HARD_RESET == reset) {
    *current_loc = 1; /* initial location */
  }

  /* validate inputs (part 2) */
  if (*current_loc <= 0 || *current_loc > 49) {
    return RV_INVALID_LOC;
  }
  if (width < 1) return RV_INVALID_ARG;

  if (SOFT_RESET == reset) {
    int i = *current_loc;
    *current_loc = reset_table[i];
  }

  /* perform binary search */
  table = data_table[*current_loc];
  size = size_table[*current_loc];
  if (0 == size) {
    result = NULL;
  } else {
    key.input = inputs[0];
    result = (trans_t *)bsearch(&key, table, size, sizeof(trans_t), data_cmp);
  }
  if (result) {
    output = result->output;
    *current_loc = result->next_loc;
  } else {
    output = RV_ERROR;
  }

  return output;
}

/* 4. main function (new API) */
RV_value monitor_ex
  (long    *states,      /* [in] */
   size_t   width,       /* [in] (min: 1) */
   RV_reset reset,       /* [in] */
   int     *current_loc) /* [in/out] */
{
  return monitor_internal(states, 1, reset, current_loc);
}

/* scalar support */
typedef struct {int key; int value;} scalar_t;

static int scalar_cmp (const void *lhs, const void *rhs)
{
  const scalar_t *_lhs = (const scalar_t *)lhs;
  const scalar_t *_rhs = (const scalar_t *)rhs;

  return (_lhs -> key - _rhs -> key);
}

static scalar_t system_drone_x_map[2] = {
  {0, 0x0}, {1, 0x1}
};

static scalar_t system_drone_y_map[2] = {
  {0, 0x0}, {1, 0x1}
};

static scalar_t system_current_action_map[5] = {
  {up, 0x6}, {no_action, 0x4}, {right, 0x2}, {down, 0x1},
  {left, 0x0}
};

/* 5. The scalar monitor interface */
RV_value monitor_scalar
  (monitor_input_t *input,
   monitor_mask_t *masks,
   RV_reset reset,
   int *current_loc)
{
  long inputs[1];
  scalar_t item, *result = NULL;
  int system_drone_x = input->system_drone_x;
  int system_drone_y = input->system_drone_y;
  int system_current_action = input->system_current_action;
  int bit, bits;

  memset((void *)inputs, 0, 1 * sizeof(long));
  item.key = system_drone_x;
  result = (scalar_t *)bsearch(&item, system_drone_x_map, 2, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x1L /* 2^0 */ : 0L;
  item.key = system_drone_y;
  result = (scalar_t *)bsearch(&item, system_drone_y_map, 2, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x2L /* 2^1 */ : 0L;
  item.key = system_current_action;
  result = (scalar_t *)bsearch(&item, system_current_action_map, 5, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = (bits >> 2) & 1;
  inputs[0] += (bit == 1) ? 0x4L /* 2^2 */ : 0L;
  bit = (bits >> 1) & 1;
  inputs[0] += (bit == 1) ? 0x8L /* 2^3 */ : 0L;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x10L /* 2^4 */ : 0L;

  return monitor_internal(inputs, 1, reset, current_loc);
}
