#!/bin/bash

location=$1
sed -i 's|step|collision_step|g' "${location}/collision_monitor.c"
sed -i 's|step|collision_step|g' "${location}/collision_monitor.h"
sed -i 's|go_slow|go_slow_collision|g' "${location}/collision_monitor.c"
sed -i 's|go_slow|go_slow_collision|g' "${location}/collision_monitor.h"
sed -i 's|step|loop_step|g' "${location}/loop_monitor.c"
sed -i 's|step|loop_step|g' "${location}/loop_monitor.h"
sed -i 's|go_slow|go_slow_loop|g' "${location}/loop_monitor.c"
sed -i 's|go_slow|go_slow_loop|g' "${location}/loop_monitor.h"
sed -i 's|s0_get|collision_s0_get|g' "${location}/collision_monitor.c"
sed -i 's|s1_get|collision_s1_get|g' "${location}/collision_monitor.c"
sed -i 's|s0_gen|collision_s0_gen|g' "${location}/collision_monitor.c"
sed -i 's|s1_gen|collision_s1_gen|g' "${location}/collision_monitor.c"
sed -i 's|s0_get|loop_s0_get|g' "${location}/loop_monitor.c"
sed -i 's|s1_get|loop_s1_get|g' "${location}/loop_monitor.c"
sed -i 's|s0_gen|loop_s0_gen|g' "${location}/loop_monitor.c"
sed -i 's|s1_gen|loop_s1_gen|g' "${location}/loop_monitor.c"

echo '_Bool collision_interface(int32_t, int32_t, int32_t, int32_t, int32_t);' >> "${location}/collision_monitor.h"
echo '#include <stdio.h>' >> "${location}/collision_monitor.c"
echo 'int32_t drone_x;' >> "${location}/collision_monitor.c"
echo 'int32_t drone_y;' >> "${location}/collision_monitor.c"
echo 'int32_t delta_x;' >> "${location}/collision_monitor.c"
echo 'int32_t delta_y;' >> "${location}/collision_monitor.c"
echo 'int32_t drone_speed;' >> "${location}/collision_monitor.c"
echo 'static _Bool slow_down;' >> "${location}/collision_monitor.c"
echo 'void go_slow_collision(void) {' >> "${location}/collision_monitor.c"
echo '  slow_down = true;' >> "${location}/collision_monitor.c"
echo '}' >> "${location}/collision_monitor.c"
echo '_Bool collision_interface(int32_t x, int32_t y, int32_t dx, int32_t dy, int32_t ds) {' >> "${location}/collision_monitor.c"
echo '  slow_down = false;' >> "${location}/collision_monitor.c"
echo '  drone_x = x;' >> "${location}/collision_monitor.c"
echo '  drone_y = y;' >> "${location}/collision_monitor.c"
echo '  delta_x = dx;' >> "${location}/collision_monitor.c"
echo '  delta_y = dy;' >> "${location}/collision_monitor.c"
echo '  drone_speed = ds;' >> "${location}/collision_monitor.c"
echo '  collision_step();' >> "${location}/collision_monitor.c"
echo '  return slow_down;' >> "${location}/collision_monitor.c"
echo '}' >> "${location}/collision_monitor.c"

echo '_Bool loop_interface(int32_t);' >> "${location}/loop_monitor.h"
echo '#include <stdio.h>' >> "${location}/loop_monitor.c"
echo 'int32_t current_action;' >> "${location}/loop_monitor.c"
echo 'static _Bool slow_down;' >> "${location}/loop_monitor.c"
echo 'void go_slow_loop(void) {' >> "${location}/loop_monitor.c"
echo '  slow_down = true;' >> "${location}/loop_monitor.c"
echo '}' >> "${location}/loop_monitor.c"
echo '_Bool loop_interface(int32_t ca) {' >> "${location}/loop_monitor.c"
echo '  slow_down = false;' >> "${location}/loop_monitor.c"
echo '  current_action = ca;' >> "${location}/loop_monitor.c"
echo '  loop_step();' >> "${location}/loop_monitor.c"
echo '  return slow_down;' >> "${location}/loop_monitor.c"
echo '}' >> "${location}/loop_monitor.c"

