#!/bin/bash

location=$1
sed -i 's|step|execute_step|' "${location}/collision_monitor.c"
sed -i 's|step|execute_step|' "${location}/collision_monitor.h"
sed -i 's|step|execute_step|' "${location}/loop_monitor.c"
sed -i 's|step|execute_step|' "${location}/loop_monitor.h"

echo '_Bool user_interface(int32_t, int32_t, int32_t, int32_t, int32_t);' >> "${location}/collision_monitor.h"
echo '#include <stdio.h>' >> "${location}/collision_monitor.c"
echo 'int32_t drone_x;' >> "${location}/collision_monitor.c"
echo 'int32_t drone_y;' >> "${location}/collision_monitor.c"
echo 'int32_t delta_x;' >> "${location}/collision_monitor.c"
echo 'int32_t delta_y;' >> "${location}/collision_monitor.c"
echo 'int32_t drone_speed;' >> "${location}/collision_monitor.c"
echo '_Bool slow_down;' >> "${location}/collision_monitor.c"
echo 'void go_slow(void) {' >> "${location}/collision_monitor.c"
echo '  slow_down = true;' >> "${location}/collision_monitor.c"
echo '}' >> "${location}/collision_monitor.c"
echo '_Bool user_interface(int32_t x, int32_t y, int32_t dx, int32_t dy, int32_t ds) {' >> "${location}/collision_monitor.c"
echo '  slow_down = false;' >> "${location}/collision_monitor.c"
echo '  drone_x = x;' >> "${location}/collision_monitor.c"
echo '  drone_y = y;' >> "${location}/collision_monitor.c"
echo '  delta_x = dx;' >> "${location}/collision_monitor.c"
echo '  delta_y = dy;' >> "${location}/collision_monitor.c"
echo '  drone_speed = ds;' >> "${location}/collision_monitor.c"
echo '  execute_step();' >> "${location}/collision_monitor.c"
echo '  return slow_down;' >> "${location}/collision_monitor.c"
echo '}' >> "${location}/collision_monitor.c"

echo '_Bool user_interface(int32_t);' >> "${location}/loop_monitor.h"
echo '#include <stdio.h>' >> "${location}/loop_monitor.c"
echo 'int32_t current_action;' >> "${location}/loop_monitor.c"
echo '_Bool slow_down;' >> "${location}/loop_monitor.c"
echo 'void go_slow(void) {' >> "${location}/loop_monitor.c"
echo '  slow_down = true;' >> "${location}/loop_monitor.c"
echo '}' >> "${location}/loop_monitor.c"
echo '_Bool user_interface(int32_t ca) {' >> "${location}/loop_monitor.c"
echo '  slow_down = false;' >> "${location}/loop_monitor.c"
echo '  current_action = ca;' >> "${location}/loop_monitor.c"
echo '  execute_step();' >> "${location}/loop_monitor.c"
echo '  return slow_down;' >> "${location}/loop_monitor.c"
echo '}' >> "${location}/loop_monitor.c"

