/******************************************************************************
 * monitor code generated by NuRV (NuRV_lite version: 1.0.0)
 *
 * LTL:  G !((((system.drone_x_stage_1 <= system.obstacles_stage_0_index_0 & system.drone_x_stage_1 >= system.obstacles_stage_0_index_0 - system.obstacle_sizes_stage_0_index_0) & system.drone_y_stage_1 <= system.obstacles_stage_0_index_1) & system.drone_y_stage_1 >= system.obstacles_stage_0_index_1 - system.obstacle_sizes_stage_0_index_0) | (((system.drone_x_stage_1 <= system.obstacles_stage_0_index_2 & system.drone_x_stage_1 >= system.obstacles_stage_0_index_2 - system.obstacle_sizes_stage_0_index_1) & system.drone_y_stage_1 <= system.obstacles_stage_0_index_3) & system.drone_y_stage_1 >= system.obstacles_stage_0_index_3 - system.obstacle_sizes_stage_0_index_1))
 *
 * nbits_obs: 26 (width: 1), nbits_all: 26 (width: 1)
 * reset_table: 1, trans_table: 1, input_filter: 0
 ******************************************************************************/

#include <stdio.h>  /* for FILE, etc. */
#include <stddef.h> /* for size_t */
#include <stdlib.h> /* for bsearch() */
#include <stdint.h> /* for int8_t, etc. */
#include <string.h> /* for memset() */
#include <assert.h> /* for assert() */

#include "monitor.h"

/* for internal per-monitor use only */
typedef struct {
  long input;
  int output;
  int next_loc;
} trans_t;

/* maximum number of elements in each line: 4 */
static trans_t data_257[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_256[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_255[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_254[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_253[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_252[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_251[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_250[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_249[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_248[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_247[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_246[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_245[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_244[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_243[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_242[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_241[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_240[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_239[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_238[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_237[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_236[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_235[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_234[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_233[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_232[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_231[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_230[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_229[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_228[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_227[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_226[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_225[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_224[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_223[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_222[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_221[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_220[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_219[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_218[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_217[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_216[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_215[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_214[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_213[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_212[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_211[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_210[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_209[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_208[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_207[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_206[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_205[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_204[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_203[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_202[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_201[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_200[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_199[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_198[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_197[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_196[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_195[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_194[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_193[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_192[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_191[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_190[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_189[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_188[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_187[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_186[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_185[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_184[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_183[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_182[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_181[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_180[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_179[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_178[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_177[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_176[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_175[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_174[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_173[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_172[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_171[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_170[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_169[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_168[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_167[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_166[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_165[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_164[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_163[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_162[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_161[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_160[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_159[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_158[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_157[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_156[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_155[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_154[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_153[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_152[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_151[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_150[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_149[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_148[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_147[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_146[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_145[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_144[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_143[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_142[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_141[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_140[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_139[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_138[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_137[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_136[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_135[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_134[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_133[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_132[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_131[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_130[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_129[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_128[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_127[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_126[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_125[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_124[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_123[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_122[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_121[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_120[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_119[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_118[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_117[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_116[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_115[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_114[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_113[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_112[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_111[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_110[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_109[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_108[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_107[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_106[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_105[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_104[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_103[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_102[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_101[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_100[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_99[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_98[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_97[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_96[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_95[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_94[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_93[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_92[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_91[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_90[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_89[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_88[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_87[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_86[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_85[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_84[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_83[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_82[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_81[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_80[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_79[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_78[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_77[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_76[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_75[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_74[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_73[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_72[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_71[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_70[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_69[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_68[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_67[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_66[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_65[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_64[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_63[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_62[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_61[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_60[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_59[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_58[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_57[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_56[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_55[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_54[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_53[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_52[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_51[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_50[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_49[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_48[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_47[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_46[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_45[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_44[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_43[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_42[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_41[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_40[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_39[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_38[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_37[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_36[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_35[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_34[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_33[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_32[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_31[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_30[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_29[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_28[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_27[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_26[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_25[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_24[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_23[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_22[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_21[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_20[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_19[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_18[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_17[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_16[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_15[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_14[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_13[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_12[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_11[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_10[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_9[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_8[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_7[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_6[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_5[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_4[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_3[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_2[1] = {{0L, 0, 0}}; /* dummy node */

static trans_t data_1[256] = {
  {0x300000L, 1, 2}, {0x300004L, 1, 3}, {0x300020L, 1, 4}, {0x300024L, 1, 5}, /* L1 */
  {0x300100L, 1, 6}, {0x300104L, 1, 7}, {0x300120L, 1, 8}, {0x300124L, 1, 9}, /* L2 */
  {0x300800L, 1, 10}, {0x300804L, 1, 11}, {0x300820L, 1, 12}, {0x300824L, 1, 13}, /* L3 */
  {0x300900L, 1, 14}, {0x300904L, 1, 15}, {0x300920L, 1, 16}, {0x300924L, 1, 17}, /* L4 */
  {0x304000L, 1, 18}, {0x304004L, 1, 19}, {0x304020L, 1, 20}, {0x304024L, 1, 21}, /* L5 */
  {0x304100L, 1, 22}, {0x304104L, 1, 23}, {0x304120L, 1, 24}, {0x304124L, 1, 25}, /* L6 */
  {0x304800L, 1, 26}, {0x304804L, 1, 27}, {0x304820L, 1, 28}, {0x304824L, 1, 29}, /* L7 */
  {0x304900L, 1, 30}, {0x304904L, 1, 31}, {0x304920L, 1, 32}, {0x304924L, 1, 33}, /* L8 */
  {0x320000L, 1, 34}, {0x320004L, 1, 35}, {0x320020L, 1, 36}, {0x320024L, 1, 37}, /* L9 */
  {0x320100L, 1, 38}, {0x320104L, 1, 39}, {0x320120L, 1, 40}, {0x320124L, 1, 41}, /* L10 */
  {0x320800L, 1, 42}, {0x320804L, 1, 43}, {0x320820L, 1, 44}, {0x320824L, 1, 45}, /* L11 */
  {0x320900L, 1, 46}, {0x320904L, 1, 47}, {0x320920L, 1, 48}, {0x320924L, 1, 49}, /* L12 */
  {0x324000L, 1, 50}, {0x324004L, 1, 51}, {0x324020L, 1, 52}, {0x324024L, 1, 53}, /* L13 */
  {0x324100L, 1, 54}, {0x324104L, 1, 55}, {0x324120L, 1, 56}, {0x324124L, 1, 57}, /* L14 */
  {0x324800L, 1, 58}, {0x324804L, 1, 59}, {0x324820L, 1, 60}, {0x324824L, 1, 61}, /* L15 */
  {0x324900L, 1, 62}, {0x324904L, 1, 63}, {0x324920L, 1, 64}, {0x324924L, 1, 65}, /* L16 */
  {0x1300000L, 1, 66}, {0x1300004L, 1, 67}, {0x1300020L, 1, 68}, {0x1300024L, 1, 69}, /* L17 */
  {0x1300100L, 1, 70}, {0x1300104L, 1, 71}, {0x1300120L, 1, 72}, {0x1300124L, 1, 73}, /* L18 */
  {0x1300800L, 1, 74}, {0x1300804L, 1, 75}, {0x1300820L, 1, 76}, {0x1300824L, 1, 77}, /* L19 */
  {0x1300900L, 1, 78}, {0x1300904L, 1, 79}, {0x1300920L, 1, 80}, {0x1300924L, 1, 81}, /* L20 */
  {0x1304000L, 1, 82}, {0x1304004L, 1, 83}, {0x1304020L, 1, 84}, {0x1304024L, 1, 85}, /* L21 */
  {0x1304100L, 1, 86}, {0x1304104L, 1, 87}, {0x1304120L, 1, 88}, {0x1304124L, 1, 89}, /* L22 */
  {0x1304800L, 1, 90}, {0x1304804L, 1, 91}, {0x1304820L, 1, 92}, {0x1304824L, 1, 93}, /* L23 */
  {0x1304900L, 1, 94}, {0x1304904L, 1, 95}, {0x1304920L, 1, 96}, {0x1304924L, 1, 97}, /* L24 */
  {0x1320000L, 1, 98}, {0x1320004L, 1, 99}, {0x1320020L, 1, 100}, {0x1320024L, 1, 101}, /* L25 */
  {0x1320100L, 1, 102}, {0x1320104L, 1, 103}, {0x1320120L, 1, 104}, {0x1320124L, 1, 105}, /* L26 */
  {0x1320800L, 1, 106}, {0x1320804L, 1, 107}, {0x1320820L, 1, 108}, {0x1320824L, 1, 109}, /* L27 */
  {0x1320900L, 1, 110}, {0x1320904L, 1, 111}, {0x1320920L, 1, 112}, {0x1320924L, 1, 113}, /* L28 */
  {0x1324000L, 1, 114}, {0x1324004L, 1, 115}, {0x1324020L, 1, 116}, {0x1324024L, 1, 117}, /* L29 */
  {0x1324100L, 1, 118}, {0x1324104L, 1, 119}, {0x1324120L, 1, 120}, {0x1324124L, 1, 121}, /* L30 */
  {0x1324800L, 1, 122}, {0x1324804L, 1, 123}, {0x1324820L, 1, 124}, {0x1324824L, 1, 125}, /* L31 */
  {0x1324900L, 1, 126}, {0x1324904L, 1, 127}, {0x1324920L, 1, 128}, {0x1324924L, 1, 129}, /* L32 */
  {0x2300000L, 1, 130}, {0x2300004L, 1, 131}, {0x2300020L, 1, 132}, {0x2300024L, 1, 133}, /* L33 */
  {0x2300100L, 1, 134}, {0x2300104L, 1, 135}, {0x2300120L, 1, 136}, {0x2300124L, 1, 137}, /* L34 */
  {0x2300800L, 1, 138}, {0x2300804L, 1, 139}, {0x2300820L, 1, 140}, {0x2300824L, 1, 141}, /* L35 */
  {0x2300900L, 1, 142}, {0x2300904L, 1, 143}, {0x2300920L, 1, 144}, {0x2300924L, 1, 145}, /* L36 */
  {0x2304000L, 1, 146}, {0x2304004L, 1, 147}, {0x2304020L, 1, 148}, {0x2304024L, 1, 149}, /* L37 */
  {0x2304100L, 1, 150}, {0x2304104L, 1, 151}, {0x2304120L, 1, 152}, {0x2304124L, 1, 153}, /* L38 */
  {0x2304800L, 1, 154}, {0x2304804L, 1, 155}, {0x2304820L, 1, 156}, {0x2304824L, 1, 157}, /* L39 */
  {0x2304900L, 1, 158}, {0x2304904L, 1, 159}, {0x2304920L, 1, 160}, {0x2304924L, 1, 161}, /* L40 */
  {0x2320000L, 1, 162}, {0x2320004L, 1, 163}, {0x2320020L, 1, 164}, {0x2320024L, 1, 165}, /* L41 */
  {0x2320100L, 1, 166}, {0x2320104L, 1, 167}, {0x2320120L, 1, 168}, {0x2320124L, 1, 169}, /* L42 */
  {0x2320800L, 1, 170}, {0x2320804L, 1, 171}, {0x2320820L, 1, 172}, {0x2320824L, 1, 173}, /* L43 */
  {0x2320900L, 1, 174}, {0x2320904L, 1, 175}, {0x2320920L, 1, 176}, {0x2320924L, 1, 177}, /* L44 */
  {0x2324000L, 1, 178}, {0x2324004L, 1, 179}, {0x2324020L, 1, 180}, {0x2324024L, 1, 181}, /* L45 */
  {0x2324100L, 1, 182}, {0x2324104L, 1, 183}, {0x2324120L, 1, 184}, {0x2324124L, 1, 185}, /* L46 */
  {0x2324800L, 1, 186}, {0x2324804L, 1, 187}, {0x2324820L, 1, 188}, {0x2324824L, 1, 189}, /* L47 */
  {0x2324900L, 1, 190}, {0x2324904L, 1, 191}, {0x2324920L, 1, 192}, {0x2324924L, 1, 193}, /* L48 */
  {0x3300000L, 1, 194}, {0x3300004L, 1, 195}, {0x3300020L, 1, 196}, {0x3300024L, 1, 197}, /* L49 */
  {0x3300100L, 1, 198}, {0x3300104L, 1, 199}, {0x3300120L, 1, 200}, {0x3300124L, 1, 201}, /* L50 */
  {0x3300800L, 1, 202}, {0x3300804L, 1, 203}, {0x3300820L, 1, 204}, {0x3300824L, 1, 205}, /* L51 */
  {0x3300900L, 1, 206}, {0x3300904L, 1, 207}, {0x3300920L, 1, 208}, {0x3300924L, 1, 209}, /* L52 */
  {0x3304000L, 1, 210}, {0x3304004L, 1, 211}, {0x3304020L, 1, 212}, {0x3304024L, 1, 213}, /* L53 */
  {0x3304100L, 1, 214}, {0x3304104L, 1, 215}, {0x3304120L, 1, 216}, {0x3304124L, 1, 217}, /* L54 */
  {0x3304800L, 1, 218}, {0x3304804L, 1, 219}, {0x3304820L, 1, 220}, {0x3304824L, 1, 221}, /* L55 */
  {0x3304900L, 1, 222}, {0x3304904L, 1, 223}, {0x3304920L, 1, 224}, {0x3304924L, 1, 225}, /* L56 */
  {0x3320000L, 1, 226}, {0x3320004L, 1, 227}, {0x3320020L, 1, 228}, {0x3320024L, 1, 229}, /* L57 */
  {0x3320100L, 1, 230}, {0x3320104L, 1, 231}, {0x3320120L, 1, 232}, {0x3320124L, 1, 233}, /* L58 */
  {0x3320800L, 1, 234}, {0x3320804L, 1, 235}, {0x3320820L, 1, 236}, {0x3320824L, 1, 237}, /* L59 */
  {0x3320900L, 1, 238}, {0x3320904L, 1, 239}, {0x3320920L, 1, 240}, {0x3320924L, 1, 241}, /* L60 */
  {0x3324000L, 1, 242}, {0x3324004L, 1, 243}, {0x3324020L, 1, 244}, {0x3324024L, 1, 245}, /* L61 */
  {0x3324100L, 1, 246}, {0x3324104L, 1, 247}, {0x3324120L, 1, 248}, {0x3324124L, 1, 249}, /* L62 */
  {0x3324800L, 1, 250}, {0x3324804L, 1, 251}, {0x3324820L, 1, 252}, {0x3324824L, 1, 253}, /* L63 */
  {0x3324900L, 1, 254}, {0x3324904L, 1, 255}, {0x3324920L, 1, 256}, {0x3324924L, 1, 257} /* L64 */
};

static int data_cmp (const void *lhs, const void *rhs)
{
  const trans_t *_lhs = (const trans_t *)lhs;
  const trans_t *_rhs = (const trans_t *)rhs;

  return (_lhs -> input - _rhs -> input);
}

static trans_t* data_table[258] = {
  NULL, data_1, data_2, data_3, data_4, data_5, data_6, data_7, /* L1 */
  data_8, data_9, data_10, data_11, data_12, data_13, data_14, data_15, /* L2 */
  data_16, data_17, data_18, data_19, data_20, data_21, data_22, data_23, /* L3 */
  data_24, data_25, data_26, data_27, data_28, data_29, data_30, data_31, /* L4 */
  data_32, data_33, data_34, data_35, data_36, data_37, data_38, data_39, /* L5 */
  data_40, data_41, data_42, data_43, data_44, data_45, data_46, data_47, /* L6 */
  data_48, data_49, data_50, data_51, data_52, data_53, data_54, data_55, /* L7 */
  data_56, data_57, data_58, data_59, data_60, data_61, data_62, data_63, /* L8 */
  data_64, data_65, data_66, data_67, data_68, data_69, data_70, data_71, /* L9 */
  data_72, data_73, data_74, data_75, data_76, data_77, data_78, data_79, /* L10 */
  data_80, data_81, data_82, data_83, data_84, data_85, data_86, data_87, /* L11 */
  data_88, data_89, data_90, data_91, data_92, data_93, data_94, data_95, /* L12 */
  data_96, data_97, data_98, data_99, data_100, data_101, data_102, data_103, /* L13 */
  data_104, data_105, data_106, data_107, data_108, data_109, data_110, data_111, /* L14 */
  data_112, data_113, data_114, data_115, data_116, data_117, data_118, data_119, /* L15 */
  data_120, data_121, data_122, data_123, data_124, data_125, data_126, data_127, /* L16 */
  data_128, data_129, data_130, data_131, data_132, data_133, data_134, data_135, /* L17 */
  data_136, data_137, data_138, data_139, data_140, data_141, data_142, data_143, /* L18 */
  data_144, data_145, data_146, data_147, data_148, data_149, data_150, data_151, /* L19 */
  data_152, data_153, data_154, data_155, data_156, data_157, data_158, data_159, /* L20 */
  data_160, data_161, data_162, data_163, data_164, data_165, data_166, data_167, /* L21 */
  data_168, data_169, data_170, data_171, data_172, data_173, data_174, data_175, /* L22 */
  data_176, data_177, data_178, data_179, data_180, data_181, data_182, data_183, /* L23 */
  data_184, data_185, data_186, data_187, data_188, data_189, data_190, data_191, /* L24 */
  data_192, data_193, data_194, data_195, data_196, data_197, data_198, data_199, /* L25 */
  data_200, data_201, data_202, data_203, data_204, data_205, data_206, data_207, /* L26 */
  data_208, data_209, data_210, data_211, data_212, data_213, data_214, data_215, /* L27 */
  data_216, data_217, data_218, data_219, data_220, data_221, data_222, data_223, /* L28 */
  data_224, data_225, data_226, data_227, data_228, data_229, data_230, data_231, /* L29 */
  data_232, data_233, data_234, data_235, data_236, data_237, data_238, data_239, /* L30 */
  data_240, data_241, data_242, data_243, data_244, data_245, data_246, data_247, /* L31 */
  data_248, data_249, data_250, data_251, data_252, data_253, data_254, data_255, /* L32 */
  data_256, data_257
};

/* number of elements in each line: 20 */
static size_t size_table[258] = {
  0, 256, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L1 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L2 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L3 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L4 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L5 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L6 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L7 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L8 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L9 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L10 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L11 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* L12 */
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/* 3. main function (old API) */
int /* [out] (0 = unknown, 1 = true, 2 = false, 3 = error) */
  monitor
    (long state,       /* [in] */
     int  reset,       /* [in] (0 = none, 1 = hard, 2 = soft) */
     int *current_loc) /* [in/out] */
{
  long states[1], base = 1L;

  states[0] = (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;
  state >>= 1;
  base <<= 1;
  states[0] += (state % 2L) * base;

  return monitor_ex (states, 1, reset, current_loc);
}

/* internal function (no input filtering) */
static RV_value monitor_internal
  (long    *inputs,      /* [in] */
   size_t   width,       /* [in] (min: 1) */
   RV_reset reset,       /* [in] */
   int     *current_loc) /* [in/out] */
{
  /* local variables */
  trans_t *table, key, *result; /* for bsearch() */
  size_t size;                  /* for bsearch() */
  RV_value output;

  /* validate inputs (part 1) */
  if (NULL == current_loc) {
    return RV_INVALID_LOC;
  }

  /* handle resets */
  if (HARD_RESET == reset) {
    *current_loc = 1; /* initial location */
  }

  /* validate inputs (part 2) */
  if (*current_loc <= 0 || *current_loc > 257) {
    return RV_INVALID_LOC;
  }
  if (width < 1) return RV_INVALID_ARG;

  /* perform binary search */
  table = data_table[*current_loc];
  size = size_table[*current_loc];
  if (0 == size) {
    result = NULL;
  } else {
    key.input = inputs[0];
    result = (trans_t *)bsearch(&key, table, size, sizeof(trans_t), data_cmp);
  }
  if (result) {
    output = result->output;
    *current_loc = result->next_loc;
  } else {
    output = RV_ERROR;
  }

  return output;
}

/* 4. main function (new API) */
RV_value monitor_ex
  (long    *states,      /* [in] */
   size_t   width,       /* [in] (min: 1) */
   RV_reset reset,       /* [in] */
   int     *current_loc) /* [in/out] */
{
  return monitor_internal(states, 1, reset, current_loc);
}

/* scalar support */
typedef struct {int key; int value;} scalar_t;

static int scalar_cmp (const void *lhs, const void *rhs)
{
  const scalar_t *_lhs = (const scalar_t *)lhs;
  const scalar_t *_rhs = (const scalar_t *)rhs;

  return (_lhs -> key - _rhs -> key);
}

static scalar_t system_drone_x_stage_0_map[7] = {
  {0, 0x0}, {1, 0x4}, {2, 0x2}, {3, 0x6},
  {4, 0x1}, {5, 0x5}, {6, 0x3}
};

static scalar_t system_drone_y_stage_0_map[7] = {
  {0, 0x0}, {1, 0x4}, {2, 0x2}, {3, 0x6},
  {4, 0x1}, {5, 0x5}, {6, 0x3}
};

static scalar_t system_drone_speed_stage_0_map[2] = {
  {1, 0x0}, {2, 0x1}
};

static scalar_t system_destination_x_stage_0_map[7] = {
  {0, 0x0}, {1, 0x4}, {2, 0x2}, {3, 0x6},
  {4, 0x1}, {5, 0x5}, {6, 0x3}
};

static scalar_t system_destination_x_stage_1_map[7] = {
  {0, 0x0}, {1, 0x4}, {2, 0x2}, {3, 0x6},
  {4, 0x1}, {5, 0x5}, {6, 0x3}
};

static scalar_t system_destination_y_stage_0_map[7] = {
  {0, 0x0}, {1, 0x4}, {2, 0x2}, {3, 0x6},
  {4, 0x1}, {5, 0x5}, {6, 0x3}
};

static scalar_t system_destination_y_stage_1_map[7] = {
  {0, 0x0}, {1, 0x4}, {2, 0x2}, {3, 0x6},
  {4, 0x1}, {5, 0x5}, {6, 0x3}
};

static scalar_t system_current_action_stage_0_map[5] = {
  {no_action, 0x4}, {right, 0x2}, {down, 0x1}, {left, 0x0},
  {up, 0x6}
};

static scalar_t system_executing_action_stage_0_map[5] = {
  {no_action, 0x4}, {right, 0x2}, {down, 0x1}, {left, 0x0},
  {up, 0x6}
};

/* 5. The scalar monitor interface */
RV_value monitor_scalar
  (monitor_input_t *input,
   monitor_mask_t *masks,
   RV_reset reset,
   int *current_loc)
{
  long inputs[1];
  scalar_t item, *result = NULL;
  int system_drone_x_stage_0 = input->system_drone_x_stage_0;
  int system_drone_y_stage_0 = input->system_drone_y_stage_0;
  int system_drone_speed_stage_0 = input->system_drone_speed_stage_0;
  int system_destination_x_stage_0 = input->system_destination_x_stage_0;
  int system_destination_x_stage_1 = input->system_destination_x_stage_1;
  int system_destination_y_stage_0 = input->system_destination_y_stage_0;
  int system_destination_y_stage_1 = input->system_destination_y_stage_1;
  int system_cell_changed_var_stage_0 = input->system_cell_changed_var_stage_0;
  int system_current_action_stage_0 = input->system_current_action_stage_0;
  int system_executing_action_stage_0 = input->system_executing_action_stage_0;
  int bit, bits;

  memset((void *)inputs, 0, 1 * sizeof(long));
  item.key = system_drone_x_stage_0;
  result = (scalar_t *)bsearch(&item, system_drone_x_stage_0_map, 7, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = (bits >> 2) & 1;
  inputs[0] += (bit == 1) ? 0x1L /* 2^0 */ : 0L;
  bit = (bits >> 1) & 1;
  inputs[0] += (bit == 1) ? 0x2L /* 2^1 */ : 0L;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x4L /* 2^2 */ : 0L;
  item.key = system_drone_y_stage_0;
  result = (scalar_t *)bsearch(&item, system_drone_y_stage_0_map, 7, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = (bits >> 2) & 1;
  inputs[0] += (bit == 1) ? 0x8L /* 2^3 */ : 0L;
  bit = (bits >> 1) & 1;
  inputs[0] += (bit == 1) ? 0x10L /* 2^4 */ : 0L;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x20L /* 2^5 */ : 0L;
  item.key = system_drone_speed_stage_0;
  result = (scalar_t *)bsearch(&item, system_drone_speed_stage_0_map, 2, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x40L /* 2^6 */ : 0L;
  item.key = system_destination_x_stage_0;
  result = (scalar_t *)bsearch(&item, system_destination_x_stage_0_map, 7, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = (bits >> 2) & 1;
  inputs[0] += (bit == 1) ? 0x80L /* 2^7 */ : 0L;
  bit = (bits >> 1) & 1;
  inputs[0] += (bit == 1) ? 0x100L /* 2^8 */ : 0L;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x200L /* 2^9 */ : 0L;
  item.key = system_destination_x_stage_1;
  result = (scalar_t *)bsearch(&item, system_destination_x_stage_1_map, 7, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = (bits >> 2) & 1;
  inputs[0] += (bit == 1) ? 0x400L /* 2^10 */ : 0L;
  bit = (bits >> 1) & 1;
  inputs[0] += (bit == 1) ? 0x800L /* 2^11 */ : 0L;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x1000L /* 2^12 */ : 0L;
  item.key = system_destination_y_stage_0;
  result = (scalar_t *)bsearch(&item, system_destination_y_stage_0_map, 7, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = (bits >> 2) & 1;
  inputs[0] += (bit == 1) ? 0x2000L /* 2^13 */ : 0L;
  bit = (bits >> 1) & 1;
  inputs[0] += (bit == 1) ? 0x4000L /* 2^14 */ : 0L;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x8000L /* 2^15 */ : 0L;
  item.key = system_destination_y_stage_1;
  result = (scalar_t *)bsearch(&item, system_destination_y_stage_1_map, 7, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = (bits >> 2) & 1;
  inputs[0] += (bit == 1) ? 0x10000L /* 2^16 */ : 0L;
  bit = (bits >> 1) & 1;
  inputs[0] += (bit == 1) ? 0x20000L /* 2^17 */ : 0L;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x40000L /* 2^18 */ : 0L;
  inputs[0] += (system_cell_changed_var_stage_0) ? 0x80000L : 0L;
  item.key = system_current_action_stage_0;
  result = (scalar_t *)bsearch(&item, system_current_action_stage_0_map, 5, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = (bits >> 2) & 1;
  inputs[0] += (bit == 1) ? 0x100000L /* 2^20 */ : 0L;
  bit = (bits >> 1) & 1;
  inputs[0] += (bit == 1) ? 0x200000L /* 2^21 */ : 0L;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x400000L /* 2^22 */ : 0L;
  item.key = system_executing_action_stage_0;
  result = (scalar_t *)bsearch(&item, system_executing_action_stage_0_map, 5, sizeof(scalar_t), scalar_cmp);
  if ((scalar_t *)NULL == result) { return RV_INVALID_ARG; }
  bits = result->value;
  bit = (bits >> 2) & 1;
  inputs[0] += (bit == 1) ? 0x800000L /* 2^23 */ : 0L;
  bit = (bits >> 1) & 1;
  inputs[0] += (bit == 1) ? 0x1000000L /* 2^24 */ : 0L;
  bit = bits & 1;
  inputs[0] += (bit == 1) ? 0x2000000L /* 2^25 */ : 0L;

  return monitor_internal(inputs, 1, reset, current_loc);
}
